imports:
    - { resource: 'services_security.yaml' }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    ConnectHolland\SecureJWTBundle\:
        resource: '../../src/{EventSubscriber,Handler,Security}'
        exclude: '../../src/Security/Http/Authentication/Authentication{Failure,Success}Handler.php'

    ConnectHolland\SecureJWTBundle\Swagger\LoginDecorator:
        decorates: 'api_platform.swagger.normalizer.api_gateway'
        arguments: [ '@ConnectHolland\SecureJWTBundle\Swagger\LoginDecorator.inner' ]
        autoconfigure: false
