services:
    connectholland.secure_jwt.two_factor_jwt.listener:
        class: ConnectHolland\SecureJWTBundle\Security\Firewall\TwoFactorJWTListener
        parent: security.authentication.listener.abstract
        abstract: true

    connectholland.secure_jwt.two_factor_jwt.provider:
        class: ConnectHolland\SecureJWTBundle\Security\Http\Authentication\Provider\TwoFactorJWTProvider
        autowire: true

